### ISSUE TITLE
Toast disappears too quickly

### ISSUE THREAD

**Issue by nsalyzyn-atimi** [blackberry/BB10-WebWorks-Samples#64] opened 2012-12-24 02:40 UTC
The toast disappears so quickly that anything longer than 2 words is unreadable.  Certainly the button version does not give enough time for somebody to click on it unless the user has the reflexes of a cat :).

Are there settings available to lengthen the time that the toast appears for?  I'm not quite sure I understand the purpose of the toast implementation in applications.

**Comment by nukulb** [comment] 2012-12-24 02:46
The options object takes timeout : [in milliseconds]

Sent from my BlackBerry device on the Rogers Wireless network.

From: nsalyzyn-atimi
Sent: Sunday, 23 December, 2012 9:40 PM
To: blackberry/BB10-WebWorks-Samples
Reply To: blackberry/BB10-WebWorks-Samples
Subject: [BB10-WebWorks-Samples] Toast disappears too quickly (#64)

The toast disappears so quickly that anything longer than 2 words is unreadable. Certainly the button version does not give enough time for somebody to click on it unless the user has the reflexes of a cat :).

Are there settings available to lengthen the time that the toast appears for? I'm not quite sure I understand the purpose of the toast implementation in applications.

\u2014
Reply to this email directly or view it on GitHubhttps://github.com/blackberry/BB10-WebWorks-Samples/issues/64.

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by nsalyzyn-atimi** [comment] 2012-12-24 03:09
Ahhh, that should probably get documented - although I'm sure it's far from high on the priority list ;) https://developer.blackberry.com/html5/apis/blackberry.ui.toast.html

How come I cannot get the dismissCallback to work?

``` javascript
blackberry.ui.toast.show("hiya!", {
    timeout : 20000,
    dismissCallback : function() {
        alert('done');
        console.log('closing');
    }
})
```

I get no alert and no console message.  Not when the "hiya!" times out, nor when I click on it.

**Comment by Gerii** [comment] 2012-12-24 09:37
Updated docs will be part of the next SDK release. https://github.com/blackberry/BB10-WebWorks-Framework/issues/485#issuecomment-11460962

**Closed as completed** 2012-12-24 16:59 UTC

**Comment by nsalyzyn-atimi** [comment] 2012-12-24 17:05
Thanks.  I'll post a separate issue for the dismissCallback
