### ISSUE TITLE
Update Samples for 10.2

### ISSUE THREAD

**Issue by timwindsor** [blackberry/BB10-WebWorks-Samples#160] opened 2013-09-30 21:36 UTC
Samples need to be updated to add a listener for 'webworksready' after the load event is received, to ensure they work properly on later 10.1 and 10.2 OS builds. The following samples add a listener for 'webworksready' without guaranteeing the document has loaded. The result is typically a white screen.

To be updated:
- [ ] Built-For-BlackBerry /cc @ctetreault 
- [ ] CustomContext /cc @ctetreault 
- [ ] EXIF-Data-Reader /cc @ctetreault 
- [ ] Facebook-OAuth-2 /cc @ctetreault
- [ ] Flurry /cc @ctetreault 
- [ ] Foursquare-Cards /cc @ctetreault 
- [ ] Foursquare-OAuth-2 /cc @ctetreault 
- [ ] Flurry /cc @ctetreault 
- [ ] Localization /cc @nmurugesu 
- [ ] Localytics /cc @ctetreault 
- [ ] Maps /cc @ctetreault 
- [ ] Orientation /cc @mimendoza 
- [ ] SetWallpaper /cc @ctetreault 
- [ ] ShareTargets /cc @ctetreault 
- [ ] Swipe-Navigation /cc @ctetreault 
- [ ] Toast /cc @ctetreault 
- [ ] Twitter-OAuth-1 /cc @ctetreault 
- [ ] WebworksWeather /cc @mimendoza
- [ ] WindowCovers /cc @ctetreault 
- [ ] childbrowser /cc @ctetreault 
- [ ] gestures /cc @ctetreault 
- [ ] shareCard /cc @ctetreault

**Comment by ctetreault** [comment] 2013-09-30 21:49
There is a massive sample update being planned right now that will address this.

All the samples need to be updated for Cordova, so it's part of that.

Sent from my BlackBerry 10 smartphone.
From: Tim Windsor
Sent: Monday, September 30, 2013 5:36 PM
To: blackberry/BB10-WebWorks-Samples
Reply To: blackberry/BB10-WebWorks-Samples
Cc: Chad Tetreault
Subject: [BB10-WebWorks-Samples] Update Samples for 10.2 (#160)

Samples need to be updated to add a listener for 'webworksready' after the load event is received, to ensure they work properly on later 10.1 and 10.2 OS builds. The following samples add a listener for 'webworksready' without guaranteeing the document has loaded. The result is typically a white screen.

To be updated:
-    Built-Fo-rBlackBerry /cc @ctetreaulthttps://github.com/ctetreault
-    CustomContext /cc @ctetreaulthttps://github.com/ctetreault
-    EXIF-Data-Reader /cc @ctetreaulthttps://github.com/ctetreault
-    Facebook-OAuth-2 /cc @ctetreaulthttps://github.com/ctetreault
-    Flurry /cc @ctetreaulthttps://github.com/ctetreault
-    Foursquare-Cards /cc @ctetreaulthttps://github.com/ctetreault
-    Foursquare-OAuth-2 /cc @ctetreaulthttps://github.com/ctetreault
-    Flurry /cc @ctetreaulthttps://github.com/ctetreault
-    Localization /cc @nmurugesuhttps://github.com/nmurugesu @astanleyhttps://github.com/astanley
-    Localytics /cc @ctetreault
-    Maps /cc @ctetreault
-    Orientation /cc (nobody)
-    SetWallpaper /cc @ctetreault
-    ShareTargets /cc @ctetreault
-    Swipe-Navigation /cc @ctetreault
-    Toast /cc @ctetreault
-    Twitter-OAuth-1 /cc @ctetreault
-    WebworksWeather /cc (nobody)
-    WindowCovers /cc @ctetreault
-    childbrowser /cc @ctetreault
-    gestures /cc @ctetreault
-    shareCard /cc @ctetreault

—

## Reply to this email directly or view it on GitHubhttps://github.com/blackberry/BB10-WebWorks-Samples/issues/160.

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by jrok** [comment] 2014-01-30 17:04
Hey Guys, Is this still in the works? I take it with the cordova integration that makes everything webworks 2.0 compatible? Will the Built for BlackBerry Boilerplate also be done soon? 

Thanks for all your hard work!

**Comment by astanley** [comment] 2014-01-30 19:09
Hi Jay,

Yes, this is in the works.  We have ported all applications to the 'new' format, and you can find them in the "WebWorks-2.0" branch for this repo:

https://github.com/blackberry/BB10-WebWorks-Samples/tree/WebWorks-2.0

Since the SDK is still in BETA, we are keeping these branches separate for now.  Once the Gold version of the SDK is launched, this branch will be merged into master.

Hope that helps,
Adam

**Comment by timwindsor** [comment] 2014-01-31 19:50
This particular issue is around some timing issues with some of these samples. They were all fixed in the update to WebWorks 2 and Cordova, but the ones here still need the fix in the version for WebWorks 1.0. We'll try to have it fixed soon.

**Closed as completed** 2014-04-02 14:59 UTC
